update=Wednesday, June 06, 2018 'PMt' 02:46:23 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[general]
version=1
[eeschema]
version=1
LibDir=Extra Libraries
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Addressable-Specialty
LibName31=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName32=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Automotive-Relays
LibName33=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Balun
LibName34=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Barrel-Audio-Connectors
LibName35=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName36=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName37=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName38=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName39=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Coaxial-Connectors-RF
LibName40=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Current-Transducers
LibName41=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_D-Sub-Connectors
LibName42=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName43=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName44=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName45=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName46=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName47=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_DC-DC-Converters
LibName48=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Digital-Isolators
LibName49=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName50=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName51=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName52=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Zener-Single
LibName53=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LCD-OLED-Graphic
LibName54=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName55=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Embedded-Microcontrollers
LibName56=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Encoders
LibName57=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName58=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName59=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Fixed-Inductors
LibName60=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Fuses
LibName61=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Gas-Sensors
LibName62=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName63=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Image-Sensors-Camera
LibName64=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName65=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName66=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName67=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName68=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Controllers
LibName69=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName70=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-I-O-Expanders
LibName71=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Modules
LibName72=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName73=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName74=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Specialized
LibName75=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_LED-Indication-Discrete
LibName76=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName77=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName78=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName79=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Comparators
LibName80=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName81=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Flip-Flops
LibName82=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName83=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Multivibrators
LibName84=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Shift-Registers
LibName85=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName86=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName87=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName88=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName89=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName90=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName91=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Memory
LibName92=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Microphones
LibName93=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName94=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks
LibName95=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName96=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName97=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName98=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Navigation-Switches-Joystick
LibName99=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName100=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName101=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName102=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName103=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName104=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Logic-Output
LibName105=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName106=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName107=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Oscillators
LibName108=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName109=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Chargers
LibName110=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Management
LibName111=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName112=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName113=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Gate-Drivers
LibName114=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-LED-Drivers
LibName115=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName116=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName117=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName118=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName119=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName120=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Supervisors
LibName121=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Thermal-Management
LibName122=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName123=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Reference
LibName124=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName125=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName126=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName127=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName128=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName129=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName130=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Programmable-Oscillators
LibName131=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Pushbutton-Switches
LibName132=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName133=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Reed-Relays
LibName134=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Resistor-Networks-Arrays
LibName135=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Amplifiers
LibName136=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Antennas
LibName137=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Demodulators
LibName138=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Detectors
LibName139=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName140=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Receivers
LibName141=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Switches
LibName142=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-ICs
LibName143=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-Modules
LibName144=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transmitters
LibName145=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName146=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName147=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName148=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName149=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Slide-Switches
LibName150=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Solid-State-Relays
LibName151=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Specialized-ICs
LibName152=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Specialized-Sensors
LibName153=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Surge-Suppression-ICs
LibName154=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Tactile-Switches
LibName155=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName156=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName157=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName158=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-SCRs
LibName159=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-TRIACs
LibName160=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Toggle-Switches
LibName161=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName162=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName163=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName164=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName165=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName166=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName167=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName168=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-JFETs
LibName169=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_Trimmer-Potentiometers
LibName170=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_TVS-Diodes
LibName171=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_TVS-Mixed-Technology
LibName172=Extra Libraries/digikey-kicad-library-master/digikey-symbols/dk_USB-DVI-HDMI-Connectors
